import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import {MAP,open,distanceField,newRound,step,position,sweptContact,nextCollector,aiDirection,DIRS,key,roundScores,rankScores,CATCH_BONUS,GAME_ROUNDS} from './dist/engine.mjs';
import {connectedPads,controlsAvailable,gamepadDirection} from './dist/input.mjs';
import {detectSpriteFrames,identityAsset,defaults} from './dist/render.mjs';
import {buildCharacterPrompt,generationRateLimit,handleCharacterApi,resetGenerationRateLimits,sanitizeCharacterName,validatePhoto} from './worker/character-api.mjs';
import {handleAppApi} from './worker/app-api.mjs';
import {cacheControlFor,resolveStaticRoute} from './worker/static-routing.mjs';
const party=()=>[{control:'wasd'},{control:'arrows'},{control:'ai'},{control:'ai'}];
function live(){const s=newRound(party());s.phase='playing';s.actors.forEach(a=>{a.human=true;a.dir=null;});return s;}
test('all coins and spawns are connected and the maze has escape loops',()=>{const count=MAP.flat().filter(c=>c==='.').length,dist=distanceField(1,19);assert.equal(dist.size,count);const s=newRound(party());for(const a of s.actors)assert.ok(dist.has(key(a.x,a.y)));assert.ok(count>150);});
test('one to four people always have one collector and three pursuers',()=>{for(let n=1;n<=4;n++){const p=Array.from({length:4},(_,i)=>({control:i<n?['wasd','arrows','pad:0','pad:1'][i]:'ai'})),s=newRound(p,2);assert.equal(s.actors.filter(a=>a.human).length,n);assert.equal(s.actors.filter(a=>a.collector).length,1);assert.equal(s.collector,2);assert.equal(s.actors.filter(a=>!a.collector).length,3);}});
test('five-second countdown prevents movement and coins, then starts gameplay',()=>{const s=newRound(party());s.actors[0].queued='down';for(let i=0;i<299;i++)step(s,1/60);assert.equal(s.phase,'countdown');assert.deepEqual(position(s.actors[0]),{x:1,y:1});for(let i=0;i<2;i++)step(s,1/60);assert.equal(s.phase,'playing');});
test('walls stop movement and buffered turns happen at the next open junction',()=>{const s=live(),a=s.actors[0];a.queued='left';step(s,1/60);assert.equal(a.x,1);assert.equal(a.target,null);a.queued='right';for(let i=0;i<14;i++)step(s,1/60);a.queued='up';for(let i=0;i<50;i++)step(s,1/60);assert.equal(a.x,5);assert.ok(position(a).y<19);assert.ok(s.coins.size<s.total);});
test('fixed simulation is deterministic and pause freezes it',()=>{const a=live(),b=live();a.actors[0].queued='up';b.actors[0].queued='up';for(let i=0;i<60;i++){step(a,1/60);step(b,1/60);}assert.deepEqual(position(a.actors[0]),position(b.actors[0]));a.phase='paused';const before=structuredClone(a);for(let i=0;i<600;i++)step(a,1/60);assert.deepEqual(a,before);});
test('crossing and touching characters are caught; separated paths are safe',()=>{assert.ok(sweptContact({x:0,y:0},{x:1,y:0},{x:1,y:0},{x:0,y:0}));assert.ok(!sweptContact({x:0,y:0},{x:1,y:0},{x:0,y:1},{x:1,y:1}));});
test('catch ends the round, records every catcher and takes precedence over the final coin',()=>{const s=live();s.coins=new Set(['1,1']);for(const index of [1,2]){s.actors[index].x=1;s.actors[index].y=1;}assert.deepEqual(step(s,1/60),['caught']);assert.equal(s.winner,'pursuers');assert.deepEqual(s.catchers,[1,2]);assert.equal(s.coins.size,1);});
test('collecting the final coin wins and cannot score twice',()=>{const s=live();s.coins=new Set(['1,1']);assert.deepEqual(step(s,1/60),['coin','win']);assert.equal(s.phase,'result');assert.equal(s.winner,'collector');assert.deepEqual(step(s,1/60),[]);});
test('four rounds rotate the collector while every player keeps their corner and controls',()=>{const p=party(),corners=[[1,1],[23,1],[1,19],[23,19]];let collector=0;const order=[];for(let round=1;round<=GAME_ROUNDS;round++){const s=newRound(p,collector,round);order.push(s.collector);assert.equal(s.round,round);assert.equal(s.elapsed,0);assert.equal(s.collected,0);assert.equal(s.countdown,5);assert.deepEqual(s.actors.map(actor=>[actor.x,actor.y]),corners);assert.deepEqual(s.actors.map(actor=>actor.control),p.map(player=>player.control));collector=nextCollector(p,collector);}assert.deepEqual(order,[0,1,2,3]);});
test('player character identity does not change when collector duty rotates',()=>{const mina={src:'/api/characters/mina/image'},p=[{control:'wasd',booth:null},{control:'arrows',booth:mina},{control:'ai',booth:null},{control:'ai',booth:null}];assert.equal(identityAsset(p,0),defaults.collector);assert.equal(identityAsset(p,1),mina);assert.equal(identityAsset(p,2),defaults.pursuer);for(let collector=0;collector<4;collector++)assert.deepEqual(newRound(p,collector).actors.map(actor=>actor.id),[0,1,2,3]);});
test('round scoring awards collected gold and 15 gold to each catcher',()=>{const s=newRound(party(),0,1);s.collected=23;s.catchers=[1,3];assert.equal(CATCH_BONUS,15);assert.deepEqual(roundScores(s),[23,15,0,15]);assert.deepEqual(rankScores([23,15,0,15]).map(entry=>entry.index),[0,1,3,2]);});
test('score ranking breaks ties by player number',()=>{assert.deepEqual(rankScores([20,30,30,10]).map(entry=>entry.index),[1,2,0,3]);});
test('AI paths stay on the maze and a stationary collector is caught',()=>{const s=newRound([{control:'wasd'},{control:'ai'},{control:'ai'},{control:'ai'}]);s.phase='playing';for(let i=0;i<3600&&s.phase==='playing';i++){for(const a of s.actors.filter(a=>!a.human)){const dir=aiDirection(a,s),d=DIRS[dir];assert.ok(open(a.x+d.x,a.y+d.y));}step(s,1/60);}assert.equal(s.winner,'pursuers');assert.ok(s.elapsed<30);});
test('custom art does not change gameplay or collision geometry',()=>{const p=party();p[0].booth={src:'arbitrary.png',cols:32,rows:4,fps:24,layout:'directional'};const s=newRound(p),plain=newRound(party());assert.deepEqual(s.actors,plain.actors);});
test('mixed keyboard/gamepad controls need all assigned devices connected',()=>{const p=[{control:'wasd'},{control:'arrows'},{control:'pad:0'},{control:'pad:2'}],pads=[{index:0,connected:true},null,{index:2,connected:true}];assert.ok(controlsAvailable(p,connectedPads(pads)));pads[2].connected=false;assert.ok(!controlsAvailable(p,connectedPads(pads)));pads[2].connected=true;assert.ok(controlsAvailable(p,connectedPads(pads)));assert.ok(!controlsAvailable(Array(4).fill({control:'ai'}),[]));});
test('gamepad deadzone, dominant stick axis, and D-pad override',()=>{assert.equal(gamepadDirection({axes:[.2,-.2]}),null);assert.equal(gamepadDirection({axes:[-.9,.2]}),'left');assert.equal(gamepadDirection({axes:[.2,.8]}),'down');assert.equal(gamepadDirection({axes:[.8,0],buttons:Array.from({length:16},(_,i)=>({pressed:i===12}))}),'up');});
test('photo character prompts preserve identity, outfit and exact sprite anchors',()=>{const prompt=buildCharacterPrompt();assert.match(prompt,/recognizable face/);assert.match(prompt,/OUTFIT FIDELITY IS ESSENTIAL/);assert.match(prompt,/do not redesign or replace them with a fantasy costume/);assert.match(prompt,/exactly 4 equal columns by 4 equal rows/);assert.match(prompt,/Cell centers are x=128, 384, 640, 896/);assert.match(prompt,/y=232 baseline/);assert.match(prompt,/true transparent alpha/);assert.match(prompt,/Row 1 faces DOWN/);assert.doesNotMatch(prompt,/Dress them as a friendly fantasy dungeon adventurer/);});
test('misaligned transparent sprite frames are detected and given stable anchors',()=>{const width=40,height=40,alpha=new Uint8Array(width*height),starts=[1,10,20,31],widths=[6,7,6,7];for(let row=0;row<4;row++)for(let col=0;col<4;col++)for(let y=row*10+1;y<=row*10+8;y++)for(let x=starts[col];x<starts[col]+widths[col];x++)alpha[y*width+x]=255;const atlas=detectSpriteFrames(alpha,width,height,4,4);assert.ok(atlas);assert.equal(atlas.frames.length,4);assert.deepEqual(atlas.frames.map(row=>row.length),[4,4,4,4]);assert.equal(atlas.maxWidth,7);assert.equal(atlas.maxHeight,8);assert.deepEqual(atlas.frames[0][3],{x:31,y:1,width:7,height:8});});
test('photo booth input validation accepts safe values and rejects unsafe uploads',()=>{assert.ok(validatePhoto(new Blob(['photo'],{type:'image/jpeg'})));assert.throws(()=>validatePhoto(new Blob(['photo'],{type:'image/gif'})),/JPEG, PNG, or WebP/);assert.throws(()=>validatePhoto({size:9*1024*1024,type:'image/png'}),/8 MB/);assert.equal(sanitizeCharacterName('  Mina   Swift  '),'Mina Swift');assert.throws(()=>sanitizeCharacterName('   '),/name/);});
test('photo booth publishes a default pass and adds its sprite to the shared gallery',async()=>{resetGenerationRateLimits();const store=new Map(),crossSite=await handleCharacterApi(new Request('https://game.test/api/characters/generate',{method:'POST',headers:{origin:'https://elsewhere.test'}}),{OPENAI_API_KEY:'test'},{store});assert.equal(crossSite.status,403);const form=new FormData();form.append('photo',new Blob(['photo'],{type:'image/jpeg'}),'player.jpg');form.append('name','Mina');let sent;const request=new Request('https://game.test/api/characters/generate',{method:'POST',headers:{origin:'https://game.test','cf-connecting-ip':'192.0.2.20'},body:form});const response=await handleCharacterApi(request,{OPENAI_API_KEY:'test-key'},{store,now:()=>1700000000000,fetchImpl:async(url,options)=>{sent={url,options};return new Response(JSON.stringify({data:[{b64_json:'iVBORw0KGgo='}]}),{status:200,headers:{'content-type':'application/json'}});}});assert.equal(response.status,201);const body=await response.json();assert.equal(body.character.name,'Mina');assert.equal(body.character.layout,'directional');assert.ok(body.claimToken.length>20);assert.match(body.passUrl,/\/pass\/\?character=.*#claim=/);assert.equal(sent.url,'https://api.openai.com/v1/images/edits');assert.equal(sent.options.body.get('model'),'gpt-image-2.5-sunburst');const catalog=await handleCharacterApi(new Request('https://game.test/api/characters'),{}, {store}),catalogBody=await catalog.json();assert.equal(catalogBody.count,1);assert.deepEqual(catalogBody.characters,[body.character]);assert.equal(JSON.stringify(catalogBody).includes(body.claimToken),false);const pass=await handleCharacterApi(new Request(`https://game.test/api/characters/${body.character.id}/pass`,{method:'POST',headers:{origin:'https://game.test','content-type':'application/json'},body:JSON.stringify({claimToken:body.claimToken})}),{}, {store});assert.equal(pass.status,200);const image=await handleCharacterApi(new Request(`https://game.test${body.character.imageUrl}`),{}, {store});assert.equal(image.status,200);assert.equal(image.headers.get('content-type'),'image/png');});
test('one lobby invitation and device controller can use any gallery character and switch slots',async()=>{
  resetGenerationRateLimits();const store=new Map(),lobbyStore=new Map(),form=new FormData();form.append('photo',new Blob(['photo'],{type:'image/jpeg'}),'player.jpg');form.append('name','Mina');
  const generated=await handleAppApi(new Request('https://game.test/api/characters/generate',{method:'POST',headers:{origin:'https://game.test','cf-connecting-ip':'192.0.2.30'},body:form}),{OPENAI_API_KEY:'test-key'},{store,lobbyStore,now:()=>1700000000000,fetchImpl:async()=>new Response(JSON.stringify({data:[{b64_json:'iVBORw0KGgo='}]}),{status:200,headers:{'content-type':'application/json'}})}),character=await generated.json();
  const created=await handleAppApi(new Request('https://game.test/api/lobbies',{method:'POST',headers:{origin:'https://game.test','content-type':'application/json'},body:'{}'}),{}, {store,lobbyStore,now:()=>1700000000000}),session=await created.json();
  assert.equal(created.status,201);assert.equal(session.lobby.slots[1].status,'open');assert.match(session.joinUrl,/\/join\/\?lobby=.*&token=/);assert.equal('slots' in session,false);
  const invitation=new URL(session.joinUrl),lobbyToken=invitation.searchParams.get('token');
  const guestToken=crypto.randomUUID(),claim=await handleAppApi(new Request(`https://game.test/api/lobbies/${session.lobby.id}/slots/2/claim`,{method:'POST',headers:{origin:'https://game.test','content-type':'application/json'},body:JSON.stringify({lobbyToken,characterId:character.character.id,guestToken})}),{}, {store,lobbyStore,now:()=>1700000000000}),claimed=await claim.json();
  assert.equal(claim.status,200);assert.equal(claimed.slot.character.name,'Mina');assert.equal(claimed.slot.ready,false);
  const occupied=await handleAppApi(new Request(`https://game.test/api/lobbies/${session.lobby.id}/slots/1/claim`,{method:'POST',headers:{origin:'https://game.test','content-type':'application/json'},body:JSON.stringify({lobbyToken,characterId:character.character.id,guestToken})}),{}, {store,lobbyStore,now:()=>1700000000000});
  assert.equal(occupied.status,409);
  const ready=await handleAppApi(new Request(`https://game.test/api/lobbies/${session.lobby.id}/slots/2/ready`,{method:'POST',headers:{origin:'https://game.test','content-type':'application/json'},body:JSON.stringify({lobbyToken,guestToken,ready:true})}),{}, {store,lobbyStore,now:()=>1700000000000}),readyBody=await ready.json();
  assert.equal(readyBody.slot.ready,true);
  const openedOne=await handleAppApi(new Request(`https://game.test/api/lobbies/${session.lobby.id}/slots/1/ai`,{method:'POST',headers:{origin:'https://game.test','content-type':'application/json'},body:JSON.stringify({hostToken:session.hostToken,ai:false})}),{}, {store,lobbyStore,now:()=>1700000000000}),openedOneBody=await openedOne.json();
  assert.equal(openedOneBody.slot.status,'open');
  const claimedOne=await handleAppApi(new Request(`https://game.test/api/lobbies/${session.lobby.id}/slots/1/claim`,{method:'POST',headers:{origin:'https://game.test','content-type':'application/json'},body:JSON.stringify({lobbyToken,characterId:character.character.id,guestToken})}),{}, {store,lobbyStore,now:()=>1700000000000}),claimedOneBody=await claimedOne.json();
  assert.equal(claimedOneBody.lobby.slots[0].status,'joined');assert.equal(claimedOneBody.lobby.slots[0].character.name,'Mina');assert.equal(claimedOneBody.lobby.slots[1].status,'open');
  const moved=await handleAppApi(new Request(`https://game.test/api/lobbies/${session.lobby.id}/slots/3/claim`,{method:'POST',headers:{origin:'https://game.test','content-type':'application/json'},body:JSON.stringify({lobbyToken,characterId:character.character.id,guestToken})}),{}, {store,lobbyStore,now:()=>1700000000000}),movedBody=await moved.json();
  assert.equal(movedBody.lobby.slots[0].status,'open');assert.equal(movedBody.lobby.slots[2].character.name,'Mina');assert.equal(movedBody.lobby.slots[2].ready,false);
});
test('photo booth reports exhausted API credits accurately',async()=>{resetGenerationRateLimits();const form=new FormData();form.append('photo',new Blob(['photo'],{type:'image/jpeg'}),'player.jpg');form.append('name','Mina');const request=new Request('https://game.test/api/characters/generate',{method:'POST',headers:{origin:'https://game.test','cf-connecting-ip':'192.0.2.21'},body:form}),response=await handleCharacterApi(request,{OPENAI_API_KEY:'test-key'},{store:new Map(),fetchImpl:async()=>new Response(JSON.stringify({error:{type:'insufficient_quota',code:'credit_balance_exhausted'}}),{status:429,headers:{'content-type':'application/json'}})});assert.equal(response.status,503);assert.match((await response.json()).error,/no API credits/);});
test('static routing serves booth, pass and join directory indexes',()=>{const assets={'/index.html':{},'/booth/index.html':{},'/pass/index.html':{},'/join/index.html':{},'/booth/booth.css':{}};assert.deepEqual(resolveStaticRoute('/',assets),{pathname:'/index.html'});for(const route of ['booth','pass','join']){assert.deepEqual(resolveStaticRoute(`/${route}/`,assets),{pathname:`/${route}/index.html`});assert.deepEqual(resolveStaticRoute(`/${route}`,assets),{redirect:`/${route}/`});}assert.deepEqual(resolveStaticRoute('/booth/booth.css',assets),{pathname:'/booth/booth.css'});assert.equal(resolveStaticRoute('/missing',assets),null);});
test('Vercel exposes explicit functions for every nested API route',()=>{const routes=['api/characters.mjs','api/characters/generate.mjs','api/characters/[id]/image.mjs','api/characters/[id]/pass.mjs','api/lobbies.mjs','api/lobbies/[id].mjs','api/lobbies/[id]/slots/[slot]/[action].mjs'];for(const route of routes)assert.ok(fs.existsSync(new URL(`./${route}`,import.meta.url)),`${route} is missing`);assert.ok(fs.existsSync(new URL('./api/_runtime.mjs',import.meta.url)));assert.equal(fs.existsSync(new URL('./api/[...path].mjs',import.meta.url)),false);const config=JSON.parse(fs.readFileSync(new URL('./vercel.json',import.meta.url),'utf8'));assert.equal(config.functions['api/**/*.mjs'].maxDuration,60);});
test('browser code and styles revalidate after deployments',()=>{assert.equal(cacheControlFor('/index.html'),'no-cache');assert.equal(cacheControlFor('/app.mjs'),'no-cache');assert.equal(cacheControlFor('/style.css'),'no-cache');assert.equal(cacheControlFor('/assets/adventurer.png'),'public, max-age=3600');const html=fs.readFileSync(new URL('./dist/index.html',import.meta.url),'utf8');assert.match(html,/style\.css\?v=frame-1/);assert.match(html,/app\.mjs\?v=fullscreen-1/);assert.match(html,/assets\/yep-event-logo\.webp/);});
test('shared lobby QR uses exact high-contrast modules sized for camera scanning',()=>{const qr=fs.readFileSync(new URL('./dist/qr.mjs',import.meta.url),'utf8'),app=fs.readFileSync(new URL('./dist/app.mjs',import.meta.url),'utf8');assert.match(qr,/qrcode\(0,'L'\)/);assert.match(qr,/cell=4,size=total\*cell/);assert.match(qr,/fillRect\(\(column\+quiet\)\*cell,\(row\+quiet\)\*cell,cell,cell\)/);assert.match(app,/dark:'#070914',light:'#ffffff'/);});
test('lobby controls reconnect instead of silently ignoring an AI click',()=>{const app=fs.readFileSync(new URL('./dist/app.mjs',import.meta.url),'utf8');assert.match(app,/if\(!lobbySession&&!await ensureLobby\(\)\)throw new Error/);assert.match(app,/lobbyRetryTimer=setTimeout\(\(\)=>ensureLobby\(\),2500\)/);});
test('a remote character reclaiming Player 1 is restored as a human player',()=>{const app=fs.readFileSync(new URL('./dist/app.mjs',import.meta.url),'utf8');assert.match(app,/if\(slot\.character&&\(previousStatus!==['"]joined['"]\|\|player\.control===['"]ai['"]\)\)assignControl\(index\)/);assert.doesNotMatch(app,/if\(index>0&&\(previousStatus/);});
test('lobby shows player numbers and fixed character names without role subtitles',()=>{const app=fs.readFileSync(new URL('./dist/app.mjs',import.meta.url),'utf8'),html=fs.readFileSync(new URL('./dist/index.html',import.meta.url),'utf8');assert.match(app,/<strong>PLAYER \$\{index\+1\}<\/strong>/);assert.match(app,/characterLabel\(playerAsset\(index\)\)/);assert.match(app,/identityAsset\(players,index\)/);assert.doesNotMatch(app,/COIN COLLECTOR|AI PURSUER|<small>\$\{role\}<\/small>/);assert.doesNotMatch(html,/booth-link|Open photo booth|Choose any available player slot/);assert.match(html,/SCAN TO<br>JOIN LOBBY/);});
test('join empty state opens the shared character lobby instead of the photo booth',()=>{const html=fs.readFileSync(new URL('./dist/join/index.html',import.meta.url),'utf8'),join=fs.readFileSync(new URL('./dist/join/join.mjs',import.meta.url),'utf8');assert.doesNotMatch(html,/href="\.\.\/booth\/"|Create a character/);assert.match(html,/id="browseCharacters"/);assert.match(html,/Open character lobby/);assert.match(html,/handoff\.css\?v=gallery-3/);assert.match(html,/join\.mjs\?v=gallery-3/);assert.match(join,/\$\('browseCharacters'\)\.onclick=openCharacterLibrary/);assert.match(join,/await loadCharacters\(\);\$\('characterLibrary'\)\.showModal\(\)/);});
test('join page changes slots through quadrants without a redundant change button',()=>{const html=fs.readFileSync(new URL('./dist/join/index.html',import.meta.url),'utf8'),join=fs.readFileSync(new URL('./dist/join/join.mjs',import.meta.url),'utf8'),css=fs.readFileSync(new URL('./dist/handoff.css',import.meta.url),'utf8');assert.doesNotMatch(html,/changeSlot|Change slot/);assert.doesNotMatch(join,/changeSlot/);assert.match(css,/\.slot-picker-actions\{display:grid;grid-template-columns:1fr;/);});
test('game shell uses a fullscreen matchmaking dialog without the removed page chrome',()=>{const html=fs.readFileSync(new URL('./dist/index.html',import.meta.url),'utf8');assert.match(html,/id="lobbyDialog"/);assert.match(html,/Ecopiana Year End Party matchmaking/);assert.match(html,/class="lobby-grid"/);assert.match(html,/class="player-rail/);assert.doesNotMatch(html,/class="topbar"/);assert.doesNotMatch(html,/class="heading"/);assert.doesNotMatch(html,/class="bottom-row"/);});
test('game HUD shows gold scores and final results use a vertically centered framed panel',()=>{const html=fs.readFileSync(new URL('./dist/index.html',import.meta.url),'utf8'),app=fs.readFileSync(new URL('./dist/app.mjs',import.meta.url),'utf8'),css=fs.readFileSync(new URL('./dist/style.css',import.meta.url),'utf8');assert.equal((html.match(/class="hud-score"/g)||[]).length,4);assert.match(html,/id="podiumScreen"/);assert.match(app,/GAME_ROUNDS/);assert.match(app,/podium-stage/);assert.match(app,/podium-top-three/);assert.match(app,/podium-fourth/);assert.match(css,/\.podium-results\{[^}]*place-items:center/);assert.match(css,/\.podium-top-three\{[^}]*width:min\(820px/);assert.match(css,/width:min\(1580px/);assert.match(css,/celestial-podium-outer-frame-v1\.png/);assert.doesNotMatch(css,/celestial-podium-card-frame-v1\.png/);assert.match(css,/\.podium-stage\{[^}]*flex-direction:column/);assert.match(css,/\.podium-fourth\{[^}]*flex-direction:row/);assert.doesNotMatch(css,/\.podium-fourth\{[^}]*position:absolute/);assert.match(css,/\.podium-fourth\{[^}]*grayscale\(1\)/);assert.ok(fs.existsSync(new URL('./dist/assets/celestial-podium-outer-frame-v1.png',import.meta.url)));assert.doesNotMatch(app,/Most gold after every player took one turn as collector/);});
test('podium celebration stays inside its frame with masthead and moving confetti',()=>{const app=fs.readFileSync(new URL('./dist/app.mjs',import.meta.url),'utf8'),css=fs.readFileSync(new URL('./dist/style.css',import.meta.url),'utf8');assert.match(app,/class="podium-event-logo"/);assert.match(app,/class="podium-confetti"/);assert.match(app,/length:42/);assert.match(css,/\.podium-screen\{[^}]*overflow:hidden/);assert.match(css,/\.podium-panel\{[^}]*padding-block:calc\(var\(--frame-h\)/);assert.match(css,/\.podium-panel:after\{[^}]*inset:calc\(var\(--frame-h\)/);assert.match(css,/animation:podium-confetti-fall/);assert.match(css,/@keyframes podium-confetti-fall/);assert.match(css,/top:calc\(100% \+ 24px\)/);assert.match(css,/@media\(prefers-reduced-motion:reduce\)\{\.podium-confetti i\{animation-duration:9s/);});

const generateRequest=(ip,name='Mina')=>{const form=new FormData();form.append('photo',new Blob(['photo'],{type:'image/jpeg'}),'player.jpg');form.append('name',name);return new Request('https://game.test/api/characters/generate',{method:'POST',headers:{origin:'https://game.test','cf-connecting-ip':ip},body:form});};
const fakeOpenAI=async()=>new Response(JSON.stringify({data:[{b64_json:'iVBORw0KGgo='}]}),{status:200,headers:{'content-type':'application/json'}});
test('a single photo booth device can make a steady stream of characters, with a configurable limit',async()=>{
  resetGenerationRateLimits();assert.equal(generationRateLimit({}),20);assert.equal(generationRateLimit({CHARACTER_RATE_LIMIT:'5'}),5);assert.equal(generationRateLimit({CHARACTER_RATE_LIMIT:'nope'}),20);
  const store=new Map(),env={OPENAI_API_KEY:'test-key'};
  for(let i=0;i<20;i++)assert.equal((await handleCharacterApi(generateRequest('192.0.2.40'),env,{store,fetchImpl:fakeOpenAI})).status,201);
  assert.equal((await handleCharacterApi(generateRequest('192.0.2.40'),env,{store,fetchImpl:fakeOpenAI})).status,429);
  resetGenerationRateLimits();const strict={...env,CHARACTER_RATE_LIMIT:'2'};
  for(let i=0;i<2;i++)assert.equal((await handleCharacterApi(generateRequest('192.0.2.41'),strict,{store,fetchImpl:fakeOpenAI})).status,201);
  assert.equal((await handleCharacterApi(generateRequest('192.0.2.41'),strict,{store,fetchImpl:fakeOpenAI})).status,429);
});
test('a shared rate limiter replaces the in-process one when a host provides it',async()=>{
  resetGenerationRateLimits();const hits=[],rateLimiter={async hit(key,now,limit,windowMs){hits.push({key,limit,windowMs});return false;}};
  const response=await handleCharacterApi(generateRequest('192.0.2.42'),{OPENAI_API_KEY:'test-key',CHARACTER_RATE_LIMIT:'7'},{store:new Map(),fetchImpl:fakeOpenAI,rateLimiter});
  assert.equal(response.status,429);assert.deepEqual(hits,[{key:'192.0.2.42',limit:7,windowMs:600000}]);
});
async function lobbyWithCharacter(){
  resetGenerationRateLimits();const store=new Map(),lobbyStore=new Map(),options={store,lobbyStore,now:()=>1700000000000,fetchImpl:fakeOpenAI};
  const character=(await (await handleAppApi(generateRequest('192.0.2.50'),{OPENAI_API_KEY:'test-key'},options)).json()).character;
  const session=await (await handleAppApi(new Request('https://game.test/api/lobbies',{method:'POST',headers:{origin:'https://game.test','content-type':'application/json'},body:'{}'}),{},options)).json();
  const lobbyToken=new URL(session.joinUrl).searchParams.get('token');
  const post=(slot,action,payload)=>handleAppApi(new Request(`https://game.test/api/lobbies/${session.lobby.id}/slots/${slot}/${action}`,{method:'POST',headers:{origin:'https://game.test','content-type':'application/json'},body:JSON.stringify(payload)}),{},options);
  const claim=(slot,guestToken=crypto.randomUUID())=>post(slot,'claim',{lobbyToken,characterId:character.id,guestToken});
  const read=async()=>(await (await handleAppApi(new Request(`https://game.test/api/lobbies/${session.lobby.id}`),{},options)).json()).lobby;
  return {session,claim,post,read};
}
test('simultaneous lobby updates from different phones are all kept',async()=>{
  const {session,claim,post,read}=await lobbyWithCharacter();
  const responses=await Promise.all([claim(2),claim(3),claim(4),post(1,'ready',{hostToken:session.hostToken,ready:true})]);
  assert.deepEqual(responses.map(response=>response.status),[200,200,200,200]);
  const lobby=await read();assert.deepEqual(lobby.slots.map(slot=>slot.status),['joined','joined','joined','joined']);assert.equal(lobby.slots[0].ready,true);
});
test('two phones racing for the same slot cannot both win it',async()=>{
  const {claim,read}=await lobbyWithCharacter();
  const statuses=(await Promise.all([claim(2),claim(2)])).map(response=>response.status).sort();
  assert.deepEqual(statuses,[200,409]);assert.equal((await read()).slots[1].status,'joined');
});
test('the removed PNG editor and control picker leave no dead code behind',()=>{
  const app=fs.readFileSync(new URL('./dist/app.mjs',import.meta.url),'utf8'),html=fs.readFileSync(new URL('./dist/index.html',import.meta.url),'utf8'),booth=fs.readFileSync(new URL('./dist/booth/booth.mjs',import.meta.url),'utf8');
  assert.equal(fs.existsSync(new URL('./dist/characters.mjs',import.meta.url)),false);assert.doesNotMatch(html,/characterDialog/);assert.doesNotMatch(app,/characterEditor|control-select|lobbyStartTimer|controlLabel/);
  const tags=[...app.matchAll(/render\.mjs\?v=([\w-]+)/g),...booth.matchAll(/render\.mjs\?v=([\w-]+)/g)].map(match=>match[1]);assert.equal(tags.length,2);assert.equal(new Set(tags).size,1);
});
